[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "chainlink/=lib/chainlink-brownie-contracts/",
    "chainlink-vrf/=lib/chainlink-brownie-contracts/contracts/src/v0.8/vrf/",
    "reentrancy-gaurd=lib/openzeppelin-contracts/contracts/utils/",
]

[lint]
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-variable"]

[fuzz]
runs = 2000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
